---
deployment:
  tasks:
    - export DEPLOYPATH=/home/talaliv1
    - /bin/cp -Rf app $DEPLOYPATH/
    - /bin/cp -Rf bootstrap $DEPLOYPATH/
    - /bin/cp -Rf config $DEPLOYPATH/
    - /bin/cp -Rf database $DEPLOYPATH/
    - /bin/cp -Rf resources $DEPLOYPATH/
    - /bin/cp -Rf routes $DEPLOYPATH/
    - /bin/cp -Rf public_html/. $DEPLOYPATH/public_html/
    - /bin/cp -f artisan $DEPLOYPATH/
    - /bin/cp -f composer.json $DEPLOYPATH/
