<?php

return [
    'groups' => [
        [
            'key'            => 'products',
            'label'          => 'سامانه‌ها',
            'mobile_heading' => 'سامانه‌ها و تابلوها',
            'width'          => 'w-72',
            'active_routes'  => [
                'public.smart-gold-board',
                'public.digital-rate-board',
                'public.gold-board-without-device',
                'public.online-gold-price-board',
                'public.currency-exchange-board',
                'public.silver-bullion-board',
                'public.demo',
                'public.app',
            ],
            'items' => [
                [
                    'route' => 'public.smart-gold-board',
                    'icon'  => '💎',
                    'title' => 'تابلوی هوشمند طلافروشی',
                    'desc'  => 'نمایش آنلاین نرخ روی تلویزیون مغازه',
                ],
                [
                    'route' => 'public.digital-rate-board',
                    'icon'  => '🖥️',
                    'title' => 'تابلو دیجیتال طلا و صرافی',
                    'desc'  => 'مانیتور نرخ لحظه‌ای طلا و صرافی',
                ],
                [
                    'route' => 'public.gold-board-without-device',
                    'icon'  => '☁️',
                    'title' => 'تابلو بدون نیاز به دستگاه',
                    'desc'  => 'حذف کامل هزینه‌های سخت‌افزاری',
                ],
                [
                    'route' => 'public.online-gold-price-board',
                    'icon'  => '⚡',
                    'title' => 'تابلو آنلاین قیمت طلا',
                    'desc'  => 'به‌روزرسانی خودکار نرخ‌های صنفی',
                ],
                [
                    'route' => 'public.currency-exchange-board',
                    'icon'  => '💱',
                    'title' => 'تابلو نرخ ارز صرافی',
                    'desc'  => 'ویژه صرافی‌ها و مراکز ارزی',
                ],
                [
                    'route' => 'public.silver-bullion-board',
                    'icon'  => '🥈',
                    'title' => 'تابلو نقره و شمش',
                    'desc'  => 'پوشش کامل شمش و گرم نقره',
                ],
            ],
            'footer_items' => [
                [
                    'route' => 'public.demo',
                    'icon'  => '▶️',
                    'title' => 'پیش‌نمایش زنده',
                    'mobile_title' => 'پیش‌نمایش زنده تابلو',
                    'class' => 'text-amber-600 dark:text-amber-400',
                ],
                [
                    'route' => 'public.app',
                    'icon'  => '📱',
                    'title' => 'دانلود اپلیکیشن و PWA',
                    'mobile_title' => 'دانلود اپلیکیشن و PWA',
                    'class' => 'text-blue-600 dark:text-blue-400',
                ],
            ],
        ],
        [
            'key'            => 'compare',
            'label'          => 'مقایسه‌ها',
            'mobile_heading' => 'مقایسه راهکارها و قیمت',
            'width'          => 'w-64',
            'active_routes'  => [
                'public.led-vs-smart-board',
                'public.compare.*',
            ],
            'items' => [
                [
                    'route' => 'public.led-vs-smart-board',
                    'icon'  => '⚡',
                    'title' => 'مقایسه با تابلوهای LED روان',
                    'desc'  => 'بررسی اقتصادی و هزینه‌ها',
                ],
                [
                    'route' => 'public.compare.tabangohar',
                    'icon'  => '⚖️',
                    'title' => 'مقایسه با تابان گوهر',
                    'desc'  => 'تفاوت سامانه ابری با مینی‌کیس',
                ],
                [
                    'route' => 'public.compare.tgju-tv',
                    'icon'  => '📊',
                    'title' => 'مقایسه با TGJU TV',
                    'desc'  => 'تخصصی بودن و پشتیبانی صنف طلا',
                ],
                [
                    'route' => 'public.compare.tablotala',
                    'icon'  => '🌐',
                    'title' => 'مقایسه با تابلوطلا دات‌کام',
                    'desc'  => 'تحت وب در برابر نرم‌افزار نصبی',
                ],
            ],
        ],
        [
            'key'             => 'tools',
            'label'           => 'ابزارها',
            'mobile_heading'  => 'ماشین‌حساب‌های تخصصی طلا',
            'width'           => 'w-72',
            'active_patterns' => [
                'tools/*',
            ],
            'active_routes' => [
                'public.gold-calculator',
            ],
            'items' => [
                [
                    'route'        => 'public.gold-calculator',
                    'icon'         => '🧮',
                    'title'        => 'ماشین حساب جامع طلا',
                    'mobile_title' => 'هاب جامع ماشین‌حساب‌های طلا',
                    'desc'         => 'محاسبه آنلاین قیمت طلا، سود و اجرت',
                    'highlight'    => true,
                ],
                [
                    'route'        => 'public.tools.gold-price',
                    'icon'         => '💰',
                    'title'        => 'محاسبه قیمت طلا',
                    'mobile_title' => 'محاسبه قیمت طلا با اجرت و سود',
                    'desc'         => 'فرمول خرید طلا از طلافروشی',
                ],
                [
                    'route'        => 'public.tools.wage-calculator',
                    'icon'         => '🔨',
                    'title'        => 'محاسبه اجرت ساخت',
                    'mobile_title' => 'ماشین‌حساب اجرت ساخت طلا',
                    'desc'         => 'درصدی و تومانی',
                ],
                [
                    'route'        => 'public.tools.second-hand-gold',
                    'icon'         => '♻️',
                    'title'        => 'طلای بدون اجرت / مستعمل',
                    'mobile_title' => 'محاسبه طلای دست دوم و متفرقه',
                    'desc'         => 'فرمول خرید طلای دست دوم',
                ],
                [
                    'route'        => 'public.tools.coin-bubble',
                    'icon'         => '🪙',
                    'title'        => 'حباب سکه آنلاین',
                    'mobile_title' => 'محاسبه‌گر حباب انواع سکه',
                    'desc'         => 'امامی، بهار آزادی، نیم و ربع',
                ],
                [
                    'route'        => 'public.tools.mesghal',
                    'icon'         => '⚖️',
                    'title'        => 'تبدیل مثقال به گرم ۱۸',
                    'mobile_title' => 'تبدیل مظنه مثقال به گرم ۱۸ عیار',
                    'desc'         => 'تبدیل مظنه به نرخ هر گرم',
                ],
                [
                    'route'        => 'public.tools.melted-gold',
                    'icon'         => '🔥',
                    'title'        => 'محاسبه طلای آبشده',
                    'mobile_title' => 'محاسبه طلای آبشده و عیار انگ',
                    'desc'         => 'تبدیل خط و انگ به گرم ۷۵۰',
                ],
                [
                    'route' => 'public.tools.karat-converter',
                    'icon'  => '🔄',
                    'title' => 'تبدیل عیارهای طلا و نقره',
                    'desc'  => '',
                ],
            ],
        ],
        [
            'key'            => 'guides',
            'label'          => 'آموزش و شهرها',
            'mobile_heading' => 'آموزش، شهرها و API',
            'width'          => 'w-64',
            'active_routes'  => [
                'public.guides*',
                'public.tv-setup-guide',
                'public.android-tv-gold-board',
                'public.cities*',
            ],
            'items' => [
                [
                    'route'        => 'public.guides',
                    'icon'         => '📚',
                    'title'        => 'دانشنامه و مقالات تخصصی',
                    'mobile_title' => 'دانشنامه و مقالات تخصصی طلا',
                    'desc'         => 'قوانین مالیات، فاکتور و سود طلا',
                    'color_type'   => 'blue',
                    'mobile_order' => 1,
                ],
                [
                    'route'        => 'public.tv-setup-guide',
                    'icon'         => '📺',
                    'title'        => 'راهنمای اتصال تلویزیون',
                    'desc'         => 'سامسونگ، ال‌جی، سونی و اسنوا',
                    'mobile_order' => 3,
                ],
                [
                    'route'        => 'public.android-tv-gold-board',
                    'icon'         => '🤖',
                    'title'        => 'راهنمای اندروید تی‌وی و باکس',
                    'desc'         => 'نصب روی انواع باکس و تلویزیون',
                    'mobile_order' => 4,
                ],
                [
                    'route'        => 'public.cities.index',
                    'icon'         => '🏙️',
                    'title'        => 'شهرهای فعال بازار طلا',
                    'mobile_title' => 'شهرهای فعال بازار طلا (۱۰ شهر)',
                    'desc'         => 'تهران، مشهد، اصفهان، همدان و...',
                    'highlight'    => true,
                    'mobile_order' => 2,
                ],
            ],
        ],
        [
            'key'            => 'dev',
            'label'          => 'API و ویجت',
            'mobile_heading' => 'آموزش، شهرها و API',
            'width'          => 'w-64',
            'active_routes'  => [
                'public.widget*',
                'public.api-docs',
            ],
            'items' => [
                [
                    'route'        => 'public.widget',
                    'icon'         => '🧩',
                    'title'        => 'ویجت نرخ طلا برای سایت‌ها',
                    'mobile_title' => 'ویجت قیمت طلا برای سایت‌ها',
                    'desc'         => 'تولید کد اختصاصی iframe',
                    'mobile_order' => 5,
                ],
                [
                    'route'        => 'public.api-docs',
                    'icon'         => '🔌',
                    'title'        => 'وب‌سرویس و API نرخ لحظه‌ای',
                    'mobile_title' => 'وب‌سرویس و API عمومی نرخ',
                    'desc'         => 'مستندات REST API و نمونه کدها',
                    'mobile_order' => 6,
                ],
            ],
        ],
    ],
];
